{"tests": [{"name": "Check trib(0)", "max_points": 0.5, "filename": "test_0", "points": 0.5, "files": [], "message": "'trib(0)' looks good\n"}, {"name": "Check trib(1)", "max_points": 0.5, "filename": "test_1", "points": 0.5, "files": [], "message": "'trib(1)' looks good\n"}, {"name": "Check trib(7)", "max_points": 1, "filename": "test_2", "points": 0, "files": [], "message": "The callable 'trib' supplied in your code failed with an exception while it was being called by the grading code:Traceback (most recent call last):\n  File \"/grade/run/code_feedback.py\", line 408, in call_user\n    return f(*args, **kwargs)\n  File \"<string>\", line 8, in trib\n  File \"<string>\", line 8, in trib\n  File \"<string>\", line 8, in trib\n  [Previous line repeated 982 more times]\n  File \"<string>\", line 2, in trib\nRecursionError: maximum recursion depth exceeded in comparison\n\n"}], "score": 0.1, "succeeded": true, "gradable": true, "max_points": 10.0, "images": []}