{"tests": [{"name": "Internal Grading Error", "filename": "error", "max_points": 1, "points": 0, "files": [], "message": "The grading code was not able to run.\nPlease notify the course staff and include this entire message,\nincluding the traceback below.\n\nThe error traceback is:\nTraceback (most recent call last):\n  File \"/usr/lib64/python3.6/unittest/suite.py\", line 163, in _handleClassSetUp\n    setUpClass()\n  File \"/grade/run/pl_unit_test.py\", line 50, in setUpClass\n    self.iter_num)\n  File \"/grade/run/pl_execute.py\", line 75, in execute_code\n    for variable in data['params']['names_for_user']:\nKeyError: 'names_for_user'\n\n"}], "score": 0.0, "succeeded": true, "gradable": false, "max_points": 1, "images": []}