{"tests": [{"name": "Internal Grading Error", "filename": "error", "max_points": 1, "points": 0, "files": [], "message": "The grading code was not able to run.\nPlease notify the course staff and include this entire message,\nincluding the traceback below.\n\nThe error traceback is:\nTraceback (most recent call last):\n  File \"/usr/lib64/python3.6/unittest/case.py\", line 60, in testPartExecutor\n    yield\n  File \"/usr/lib64/python3.6/unittest/case.py\", line 622, in run\n    testMethod()\n  File \"/grade/run/pl_helpers.py\", line 58, in wrapped\n    f(Test_instance)\n  File \"/grade/run/filenames/test.py\", line 20, in test_0\n    if self.ref.function == 'is_palindrome_all':\nAttributeError: 'answerTuple' object has no attribute 'function'\n\n"}], "score": 0.0, "succeeded": true, "gradable": false, "max_points": 10, "images": []}