{"tests": [{"name": "Internal Grading Error", "filename": "error", "max_points": 1, "points": 0, "files": [], "message": "The grading code was not able to run.\nPlease notify the course staff and include this entire message,\nincluding the traceback below.\n\nThe error traceback is:\nTraceback (most recent call last):\n  File \"/usr/lib64/python3.6/unittest/case.py\", line 60, in testPartExecutor\n    yield\n  File \"/usr/lib64/python3.6/unittest/case.py\", line 622, in run\n    testMethod()\n  File \"/grade/run/pl_helpers.py\", line 58, in wrapped\n    f(Test_instance)\n  File \"/grade/run/filenames/test.py\", line 15, in test_0\n    if Feedback.check_scalar(\"lcs(0)\", self.ref.lcs(\"crows eat yay\", \"ows eat \"), user_val):\n  File \"/grade/run/code_feedback.py\", line 384, in check_scalar\n    if rtol is not None and abs(ref-data) < abs(ref)*rtol:\nTypeError: unsupported operand type(s) for -: 'str' and 'int'\n\n"}], "score": 0.0, "succeeded": true, "gradable": false, "max_points": 1, "images": []}